name: odoo_client
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: ^2.0.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.6
  flutter_easyloading: ^1.0.1
  sprintf: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true